DECLARE
    V_FIRST_NAME VARCHAR2(20);
    V_SALARY     NUMBER(8, 2);
BEGIN
    SELECT FIRST_NAME, SALARY
    INTO V_FIRST_NAME, V_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;

    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME || ' has salary ' || V_SALARY);
end;