DECLARE
    V_FNAME EMPLOYEES.FIRST_NAME%TYPE;
    V_LNAME EMPLOYEES.LAST_NAME%TYPE;
    V_PHONE EMPLOYEES.PHONE_NUMBER%TYPE;
BEGIN

    SELECT FIRST_NAME, LAST_NAME, PHONE_NUMBER
    INTO V_FNAME, V_LNAME, V_PHONE
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 101;

    DBMS_OUTPUT.PUT_LINE(V_FNAME || ' ' || V_LNAME ||
                         ' phone number ' || V_PHONE);
end;

DECLARE
    V_EMPLOYEE EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO V_EMPLOYEE FROM EMPLOYEES WHERE EMPLOYEE_ID = 102;
    DBMS_OUTPUT.PUT_LINE(V_EMPLOYEE.FIRST_NAME || ' ' || V_EMPLOYEE.LAST_NAME ||
                         ' phone number ' || V_EMPLOYEE.PHONE_NUMBER);
end;