CREATE SEQUENCE USERS_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

DROP TABLE USERS PURGE;

CREATE TABLE USERS(
    USER_ID NUMBER DEFAULT USERS_SEQ.nextval,
    USER_NAME VARCHAR2(20),
    GENDER CHAR(1),
    CONSTRAINT CK_GENDER_USER CHECK (GENDER IN ('M','F')),
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

INSERT INTO USERS (USER_ID, USER_NAME, GENDER)
VALUES  (DEFAULT, 'Andi', 'M');

INSERT INTO USERS (USER_NAME, GENDER)
VALUES  ('Asep', 'M');

select * from USERS;
TRUNCATE TABLE USERS;

ALTER SEQUENCE USERS_SEQ RESTART START WITH 1;


CREATE INDEX IDX_EMP_BY_FNAME ON EMPLOYEES(FIRST_NAME);

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
