CREATE OR REPLACE PROCEDURE PRO_GET_EMP_BY_JOB (P_JOB_ID VARCHAR2)
IS
C_EMP SYS_REFCURSOR;
BEGIN
    OPEN C_EMP FOR
        SELECT FIRST_NAME, SALARY, JOB_TITLE
            FROM EMPLOYEES JOIN JOBS USING (JOB_ID)
    WHERE JOB_ID = P_JOB_ID;
    DBMS_SQL.RETURN_RESULT(C_EMP);
end;

    SELECT * FROM JOBS;

BEGIN
    PRO_GET_EMP_BY_JOB('FI_ACCOUNT');
END;