CREATE OR REPLACE FUNCTION FUNC_GET_AVG_SALARY_DEP(
    P_DEP_ID DEPARTMENTS.DEPARTMENT_ID%TYPE
) RETURN NUMBER
    IS
    V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT AVG(SALARY)
    INTO V_SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = P_DEP_ID;
    RETURN V_SALARY;
end;

    DECLARE
        V_RESULT NUMBER;
BEGIN
        V_RESULT := FUNC_GET_AVG_SALARY_DEP(10);
    DBMS_OUTPUT.PUT_LINE(V_RESULT);
end;

