DECLARE
    V_FNAME  EMPLOYEES.FIRST_NAME%TYPE;
    V_LNAME  EMPLOYEES.LAST_NAME%TYPE;
    V_SALARY EMPLOYEES.SALARY%TYPE;
    V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE := :EMP_ID;
--     EXCEPTION DECLARE
    EX_VALID_INP_ID EXCEPTION;
BEGIN
    IF V_EMP_ID = 0 THEN
        RAISE EX_VALID_INP_ID;
    end if;

    SELECT FIRST_NAME, LAST_NAME, SALARY
    INTO V_FNAME, V_LNAME, V_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = V_EMP_ID;

    DBMS_OUTPUT.PUT_LINE('OUTSIDE');

EXCEPTION
    WHEN EX_VALID_INP_ID THEN
        DBMS_OUTPUT.PUT_LINE('Employee id must greater then 0');
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Employee id ' || V_EMP_ID || ' not exsits');
end;