DECLARE
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE ;
    V_DEP_ID          NUMBER := :DEP_INP;
    V_TOTAL_DEP NUMBER;

    EX_VALID_DEP_ID EXCEPTION;
    PRAGMA EXCEPTION_INIT ( EX_VALID_DEP_ID, -20001 );
BEGIN
    SELECT COUNT(*) INTO V_TOTAL_DEP
                    FROM DEPARTMENTS;
    V_TOTAL_DEP := V_TOTAL_DEP * 10;

    IF (MOD(V_DEP_ID, 10) <> 0 OR V_DEP_ID > V_TOTAL_DEP) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Department id is not valid');
    end if;

    SELECT DEPARTMENT_NAME
    INTO V_DEPARTMENT_NAME
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = V_DEP_ID;

EXCEPTION
    WHEN EX_VALID_DEP_ID THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);

end;