DECLARE
    CURSOR C_EMP_JOB IS
        SELECT FIRST_NAME, LAST_NAME, JOB_TITLE
        FROM EMPLOYEES
                 JOIN JOBS USING (JOB_ID);
    V_EMP_JOB C_EMP_JOB%ROWTYPE;
BEGIN
    OPEN C_EMP_JOB;
    LOOP
        FETCH C_EMP_JOB INTO V_EMP_JOB;
        EXIT WHEN C_EMP_JOB%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_EMP_JOB.FIRST_NAME || ' ' || V_EMP_JOB.LAST_NAME || ' ' || V_EMP_JOB.JOB_TITLE);
    end loop;
    CLOSE C_EMP_JOB;
end;