CREATE OR REPLACE TRIGGER BI_REGIONS
    BEFORE INSERT
    ON REGIONS
    FOR EACH ROW
    DECLARE
        V_USER VARCHAR2(20);
BEGIN
    SELECT USER INTO V_USER FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('Successfully to insert Region by ' || V_USER);
end;

select * from REGIONS;
INSERT INTO REGIONS VALUES (7,'Africa');