CREATE TABLE REGION_AUDIT
(
    NEW_NAME   VARCHAR2(30),
    OLD_NAME   VARCHAR2(30),
    USER_NAME  VARCHAR2(30),
    OPERATION  VARCHAR2(30),
    ENTRY_DATE DATE
);

CREATE OR REPLACE TRIGGER TR_REGIONS
    BEFORE INSERT OR UPDATE OR DELETE
    ON REGIONS
    FOR EACH ROW
DECLARE
    V_USER VARCHAR2(30);
    V_DATE DATE;
BEGIN
    SELECT USER, SYSDATE INTO V_USER, V_DATE FROM DUAL;
    IF INSERTING THEN
        INSERT INTO REGION_AUDIT VALUES (:NEW.REGION_NAME, NULL, V_USER, 'Insert', V_DATE);
    ELSIF UPDATING THEN
        INSERT INTO REGION_AUDIT VALUES (:NEW.REGION_NAME, :OLD.REGION_NAME, V_USER, 'Update', V_DATE);
    ELSIF DELETING THEN
        INSERT INTO REGION_AUDIT VALUES (NULL, :OLD.REGION_NAME, V_USER, 'Delete', V_DATE);
    end if;
end;

SELECT * FROM REGIONS;
SELECT * FROM REGION_AUDIT;

DELETE FROM REGIONS WHERE REGION_ID = 7;
INSERT INTO REGIONS VALUES (7,'Asyiapp');
UPDATE REGIONS SET REGION_NAME = 'Africa' where REGION_ID = 7;