CREATE OR REPLACE VIEW VW_REGIONS_COUNTRIES AS
SELECT R.REGION_ID, R.REGION_NAME, C.COUNTRY_ID, C.COUNTRY_NAME
FROM REGIONS R
         JOIN COUNTRIES C on R.REGION_ID = C.REGION_ID;

SELECT *
FROM VW_REGIONS_COUNTRIES;
INSERT INTO VW_REGIONS_COUNTRIES;

SELECT * FROM REGIONS;
SELECT * FROM COUNTRIES;

INSERT INTO VW_REGIONS_COUNTRIES
values (7, 'Africa', 'SA', 'South Africa');

CREATE OR REPLACE TRIGGER IO_INSERT_VW_REGIONS_COUNTRIES
    INSTEAD OF INSERT
    ON VW_REGIONS_COUNTRIES
    FOR EACH ROW
BEGIN
    INSERT INTO REGIONS VALUES (:NEW.REGION_ID, :NEW.REGION_NAME);
    INSERT INTO COUNTRIES VALUES (:NEW.COUNTRY_ID, :NEW.COUNTRY_NAME, :NEW.REGION_ID);
end;