DECLARE
    TYPE NESTED_NAME IS TABLE OF VARCHAR2(20);
    V_NESTED_NAME NESTED_NAME := NESTED_NAME('Najim', 'Saga', 'Andi', 'Asep', 'Unggul', 'Harva');
BEGIN
    V_NESTED_NAME(2) := 'Michel';

    FOR V_IDX IN 1..V_NESTED_NAME.COUNT
        LOOP
            DBMS_OUTPUT.PUT_LINE(V_NESTED_NAME(V_IDX));
        end loop;
end;

-- Create Nested Collection in Schema Object
CREATE OR REPLACE TYPE NESTED_PHONE_NUMBER IS TABLE OF VARCHAR2(12);

CREATE TABLE PROFIL(
    USERNAME VARCHAR2(20),
    PHONE_NUMBER NESTED_PHONE_NUMBER
)NESTED TABLE PHONE_NUMBER STORE AS NT_PHONE_NUMBER

INSERT INTO PROFIL VALUES ('ANDI', NESTED_PHONE_NUMBER('08122233344','08133344455'));
SELECT * FROM PROFIL;

DROP TYPE NESTED_PHONE_NUMBER;