CREATE OR REPLACE TYPE JS AS OBJEC

DECLARE
    TYPE INBLOCK_VRY IS VARRAY(5) OF NUMBER;
    V_INBLOCK_VRY INBLOCK_VRY := INBLOCK_VRY();
BEGIN
    FOR V_IDX IN 1..V_INBLOCK_VRY.LIMIT
        LOOP
            V_INBLOCK_VRY.extend;
            V_INBLOCK_VRY(V_IDX) := 30*V_IDX;
            DBMS_OUTPUT.PUT_LINE(V_INBLOCK_VRY(V_IDX));
        end loop;
end;

DECLARE
    TYPE NAME_VRY IS VARRAY(5) EMPLOYEES.FIRST_NAME%TYPE;
    V_NAME_VRY NAME_VRY := NAME_VRY();

    V_COUNTER NUMBER := 1;

    CURSOR C_EMP IS
    SELECT FIRST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID < 200;

    V_EMP C_EMP%rowtype;
BEGIN
    FOR V_EMP IN C_EMP
    LOOP
        EXIT WHEN C_EMP%NOTFOUND;
        V_NAME_VRY.extend;
        V_NAME_VRY(V_COUNTER) := V_EMP.FIRST_NAME;
        DBMS_OUTPUT.PUT_LINE(V_NAME_VRY(V_COUNTER));
        V_COUNTER := V_COUNTER + 1;
        end loop;
end;

