DECLARE
    TYPE BOOKS IS TABLE OF NUMBER
        INDEX BY VARCHAR2(20);
    V_BOOKS BOOKS;
BEGIN
    V_BOOKS('Oracle 18c') := 2019;
    V_BOOKS('MySQL') := 1990;
    DBMS_OUTPUT.PUT_LINE(V_BOOKS('Oracle 18c'));
    DBMS_OUTPUT.PUT_LINE(V_BOOKS('MySQL'));
    DBMS_OUTPUT.PUT_LINE(TO_NUMBER(LPAD('10000',12,'0')));
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'MONTH'));
end;


