DECLARE
    V_TOTAL_ROW NUMBER;
BEGIN
    UPDATE EMPLOYEES SET SALARY = SALARY * 1.5;
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EMPOYEE UPDATED');
    ELSE
        V_TOTAL_ROW := SQL%ROWCOUNT;
        DBMS_OUTPUT.PUT_LINE(V_TOTAL_ROW);
    end if;
end;

SELECT * FROM EMPLOYEES;
ROLLBACK;
