DECLARE
    V_FNAME  EMPLOYEES.FIRST_NAME%TYPE;
    V_SALARY EMPLOYEES.SALARY%TYPE;
    CURSOR C_EMP IS
        SELECT FIRST_NAME, SALARY
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID < 105;
BEGIN
    OPEN C_EMP;
    LOOP
        FETCH C_EMP INTO V_FNAME, V_SALARY;
        DBMS_OUTPUT.PUT_LINE(V_FNAME || ' has salary ' || V_SALARY);
        EXIT WHEN C_EMP%NOTFOUND;
    end loop;
    CLOSE C_EMP;
end;