DECLARE
    V_FNAME     EMPLOYEES.FIRST_NAME%TYPE;
    V_JOB_TITLE JOBS.JOB_TITLE%TYPE;
    CURSOR C_EMP_JOBS(P_DEP_ID DEPARTMENTS.DEPARTMENT_ID%TYPE) IS
        SELECT DISTINCT FIRST_NAME, J.JOB_TITLE
        FROM EMPLOYEES
                 JOIN JOBS J on EMPLOYEES.JOB_ID = J.JOB_ID
        WHERE DEPARTMENT_ID = P_DEP_ID;
BEGIN
    OPEN C_EMP_JOBS(20);
    LOOP
        FETCH C_EMP_JOBS INTO V_FNAME, V_JOB_TITLE;
        EXIT WHEN C_EMP_JOBS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_FNAME || ' work as ' || V_JOB_TITLE);
    end loop;
    CLOSE C_EMP_JOBS;
end ;

